#!/usr/bin/env bash
source "$(dirname "$0")/common.sh"
require_docker
archive="$(realpath "${1:?Usage: bash scripts/restore.sh /absolute/backup.tar.gz}")"
[[ -f "$archive" && -f "$archive.env.tar.gz" ]] || { echo 'Backup and matching configuration required'; exit 1; }
read -r -p 'Restore replaces current data. Type RESTORE to confirm: ' answer
[[ "$answer" == RESTORE ]] || exit 1
bash scripts/backup.sh
dc stop backend frontend
# Archives are generated by backup.sh; validate entry prefixes before extraction.
tar -tzf "$archive" | awk '$0 !~ /^data\// || $0 ~ /(^|\/)\.\.(\/|$)/ {bad=1} END {exit bad}'
tar -tzf "$archive.env.tar.gz" | awk '$0 != ".env" {bad=1} END {exit bad}'
dc run --rm --no-deps --user root --entrypoint python -v "$(dirname "$archive"):/backup:ro" backend -c 'import pathlib,shutil,tarfile,sys,os; root=pathlib.Path("/data"); [shutil.rmtree(p) if p.is_dir() and not p.is_symlink() else p.unlink() for p in root.iterdir()]; tarfile.open(sys.argv[1]).extractall("/",filter="data"); [os.chown(p,10001,10001) for p in [root,*root.rglob("*")]]' "/backup/$(basename "$archive")"
tar -xzf "$archive.env.tar.gz" -C "$ROOT"
dc up -d --wait --wait-timeout 180
bash scripts/status.sh
